{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:57:04,213 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:04,215 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<queue.Queue at 0x1168beac8>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:57:07,885 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:07,887 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:08,033 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:08,034 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:11,814 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:11,816 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:12,428 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:12,430 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:14,705 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:14,707 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:16,604 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:16,606 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:57:17,958 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:17,959 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:21,960 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:21,962 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:22,259 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:22,260 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:26,750 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:26,752 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:30,248 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:30,249 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:34,855 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:34,857 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:57:36,084 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:36,086 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:38,520 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:38,523 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:45,299 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:45,299 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:50,215 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:50,216 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:50,829 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:50,831 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:53,649 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:57:53,651 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:58:07,727 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:07,739 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:11,120 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:11,122 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:12,051 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:12,053 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:15,905 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:15,907 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:21,192 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:21,193 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:26,772 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:26,775 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:58:38,168 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:38,169 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:42,096 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:42,107 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:42,457 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:42,460 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:47,047 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:47,049 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:57,128 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:58:57,130 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:01,486 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:01,488 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:59:21,199 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:21,200 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:25,506 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:25,508 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:26,062 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:26,064 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:30,848 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:30,850 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:31,894 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:31,895 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:37,736 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:37,738 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 01:59:55,861 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 01:59:55,865 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:00,162 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:00,164 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:01,392 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:01,396 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:06,306 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:06,307 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:08,150 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:08,151 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:13,990 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:13,992 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 02:00:30,467 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:30,480 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:34,768 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:34,770 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:36,595 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:36,597 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:41,553 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:41,554 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:44,291 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:44,294 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:49,825 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:00:49,828 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 02:01:05,249 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:05,251 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:09,598 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:09,600 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:12,047 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:12,050 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:17,440 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:17,450 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:20,342 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:20,344 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:26,180 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:26,182 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-06-23 02:01:39,889 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2020-06-23 02:01:39,891 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 380, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/ext/updater.py\", line 341, in polling_action_cb\n",
      "    allowed_updates=allowed_updates)\n",
      "  File \"<decorator-gen-155>\", line 2, in get_updates\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 70, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/bot.py\", line 2136, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 334, in post\n",
      "    **urlopen_kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegram/utils/request.py\", line 249, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "from telegram.ext import Updater\n",
    "from telegram.ext import MessageHandler, Filters, CommandHandler\n",
    "updater = Updater(token='1213010143:AAGDKGqY9v1QdO3W0RlWIWkcAd2ToFwmQhU', use_context=True)\n",
    "\n",
    "dispatcher = updater.dispatcher\n",
    "\n",
    "def crawl(countryCode):\n",
    "    import json\n",
    "    import sys\n",
    "    import pandas as pd\n",
    "    import requests\n",
    "    import matplotlib.pyplot as plt\n",
    "\n",
    "    URL = \"https://api.thevirustracker.com/free-api?countryTimeline=\"\n",
    "    res = requests.get(URL + countryCode)\n",
    "    arr = res.json()\n",
    "    items = arr['timelineitems'][0]\n",
    "    dates=list(items.keys())\n",
    "    dates.remove(dates[-1])\n",
    "    caseCount = [(items[key]['total_cases'])for key in items if key!='stat']\n",
    "\n",
    "    x = dates\n",
    "    y = caseCount\n",
    "    plt.clf()\n",
    "    plt.title(countryCode)\n",
    "    plt.plot(x, y)\n",
    "    plt.xlabel('date')\n",
    "    plt.ylabel('case')\n",
    "    plt.savefig('result.png')\n",
    "\n",
    "def start(update, context):\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text=\"Enter country code\")\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text=\"country code examples: TW-Taiwan, US-USA, DE-Germany\")\n",
    "\n",
    "def echo(update, context):\n",
    "    txt = update.message.text\n",
    "    crawl(txt)\n",
    "    context.bot.sendPhoto(chat_id=update.effective_chat.id, photo=open('result.png', 'rb'), caption=\"date-cases line chart\")\n",
    "\n",
    "echo_handler = MessageHandler(Filters.text & (~Filters.command), echo)\n",
    "dispatcher.add_handler(echo_handler)\n",
    "start_handler = CommandHandler('start', start)\n",
    "dispatcher.add_handler(start_handler)\n",
    "updater.start_polling()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
